### ISSUE TITLE
Longitude wrapping

### ISSUE THREAD

**Issue by claustres** [IHCantabria/Leaflet.CanvasLayer.Field#8]
I wonder if it could be possible to integrate in your library the management of the longitude wrapping. Indeed, some input data grid are often specified in range [0, 360] and not [-180, 180]. One might think it is the responsability of the calling code to setup data according to your underlying model however it can be tricky because this means you have to switch all the values in the data array, which leads to performance issues.

As I've already managed something similar (look at https://github.com/weacast/weacast-core/blob/master/src/grid.js#L98) I can say this does not affect the logic behind the data grid (ie cell management, interpolation, etc.) so it is far more simple to manage this at low-level. However you will have to check the longitude range in each function taking a longitude as input. For example when creating the image in the ScalarLayer you should wrap the longitude according to the underlying bounds of the data grid (i.e. add 360 to negative longitudes if the grid bound is [0, 360] and not [-180, 180]). Leaflet may also have some utilities to do so (e.g. http://leafletjs.com/reference-1.1.0.html#latlng-wrap or http://leafletjs.com/reference-1.1.0.html#util-wrapnum). You will also have to take care to the reverse way, meaning if you create Leaflet LatLng objects from the grid in range [0,360] you will have to wrap longitudes in the range [-180,180].

Let me know what you think about it, I will try to help if required.

**Comment by VictorVelarde** [comment]
Hi,
I agree it is an interesting use case. I will have to find some time to look at it.

**Comment by VictorVelarde** [comment]
Hi @claustres 

Sorry for the delay. I've just release a v1.1.0 version, with longitude wrapping.
I've tested it with just one dataset so I'd be pleased if you could test it with yours.

Let me know if you find any problem.

**Comment by claustres** [comment]
No problem great job ! I will tell you as soon as I can test, probably next week.Le 29 juil. 2017 12:54 AM, Víctor Velarde <notifications@github.com> a écrit :Hi @claustres
Sorry for the delay. I've just release a v1.1.0 version, with longitude wrapping.
I've tested it with just one dataset so I'd be pleased if you could test it with yours.
Let me know if you find any problem.

**Comment by claustres** [comment]
Just tested and it seems to work really fine in Weacast:
![weacast-colormap-gfs](https://user-images.githubusercontent.com/2647117/28767268-4f4864ae-75d3-11e7-8717-f44132d46e39.png)

As far as I can see the only minor issue detected is that along the wrapping line interpolation does not seem to occur correctly (or maybe there is none):
![weacast-colormap-gfs-interpolationwrapping](https://user-images.githubusercontent.com/2647117/28767294-5ad4e496-75d3-11e7-93f8-72f1306a01bd.png)

I add a similar issue and addressed this by "virtually" duplicating the first column as last column of the grid when computation occurred along the wrapping line: https://github.com/weacast/weacast-core/blob/master/src/grid.js#L103.

I also wonder if this is correct https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/blob/master/src/Field.js#L98 in the case where we don't have a whole world but simply a small part. Should it be something like:
```
if (this.xurCorner > 180) xmax = this.xurCorner - 180
if (this.xllCorner > 180) xmin = this.xllCorner - 180
```

**Comment by VictorVelarde** [comment]
Thank you so much @claustres 

I think I will try the same duplicating approach. And yes, I was assuming a whole world raster, but your snippet gives it more flexibility.

**Comment by VictorVelarde** [comment]
Hi @claustres 

Duplicating first column would be just something like this... isn't it?

```javascript
_clampColumnIndex(ii) {
        let i = ii;
        if (ii < 0) {
            i = 0;
        }
        let maxCol = (this.nCols - 1);
        if (ii > maxCol) {
            i = (this.longitudeNeedsToBeWrapped) ? 0 : maxCol;
        }
        return i;
    }

```

**Comment by claustres** [comment]
Yes it looks correct although I don't have the knowledge of your whole interpolation process.

**Comment by VictorVelarde** [comment]
Hi,

I've released v1.2.1, with 'virtual duplication of first column'. That should fix the  problem along the interpolation line.

Regarding to managing smaller wrapped rasters, I can't find a 100% satisfactory solution, despite of your help. I just have 2 working cases: the whole world or xmin&xmax both over 180º: https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/blob/master/src/Field.js#L99

This fullfills my current needs but I don't know if it is a big issue for you.

**Comment by claustres** [comment]
It seems the issue is still there or I have a bug in my code, however wind seems to be correct so I doubt of it:
![interpolation-bug](https://user-images.githubusercontent.com/2647117/28861881-39c6f3fc-7763-11e7-9cb0-51e5e140062b.png)
The problem seems to have moved one column to the left, I guess you should duplicate the first column only and not the last as well.

I think you should check if the bounds are > 180° before adjusting otherwise if you have a small part in the negative side of the world this will break. You probably have to adjust as well min/max if the bounds cross the 0°, something like this:
```
if (this.xurCorner > 180) xmax = this.xurCorner - 360
if (this.xllCorner > 180) xmin = this.xllCorner - 360
if (xmax < xmin) swap(xmin, xmax)
```

**Comment by VictorVelarde** [comment]
That's true, the problem is still there. I will have to dedicate more time to fix it.
Thx for your collaboration!

**Comment by VictorVelarde** [comment]
Hi again, @claustres 

I've just published a new v1.3.3 release that deals with this issue.
I will be glad if you could test it with your datasets. 

Thanks in advance!

**Comment by claustres** [comment]
Thanks, will have a look as soon as possible

**Comment by VictorVelarde** [comment]
Thx Luc, 
I appreciate it

**Comment by claustres** [comment]
It seems to be still there on my side, maybe I have to investigate more so that we are sure the problem is not coming from your code ?
![capture-2](https://user-images.githubusercontent.com/2647117/31395325-cedd3d76-ade0-11e7-9e3c-63fa2ad6e421.png)

**Comment by VictorVelarde** [comment]
Sorry to hear that, Luc.

I have used https://ihcantabria.github.io/Leaflet.CanvasLayer.Field/example_ScalarField_360.html as a reference for this issue. I had the very same problem than you, with that artifact near 0º longitude, and fixed it with this release. 

Could I have a look at your dataset?

**Comment by claustres** [comment]
Maybe if you tell me how you retrieved/transformed this sample data this might help me locate the problem.

**Comment by claustres** [comment]
My bad, actually I did not upgrade the right app, sorry. I have now a greater problem: the visualization does not work at all anymore :-( I have to investigate more, could you see any change between 1.2x and 1.3x that  require some code adaptation ? Thanks

**Comment by VictorVelarde** [comment]
Well, there has been quite a lot of small internal changes (https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/compare/v1.2.0...v1.3.3), but not many 'external' ones.

A potential breaking change could be the deletion of `L.ColorScale` (not `L.Control.ColorBar`), but I would be surprised if you were using it. It was an ongoing work to replace 'chromajs.scale', but it happened to be slower.

The rest of changes (e.g. new arrow style renderer, compatibility with different x-y pixel size in geotiff and this interpolation adjustment for wrapped rasters...) should not break your client... 

I would be pleased to help you, but I would need more context, such as an accessible example

**Comment by claustres** [comment]
I think my whole usage of your module is located [here](https://github.com/weacast/weacast-client/blob/master/src/layers/color-layer.js). I uploaded some of my [test data](https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/files/1375580/data.zip) as JSON. The data passed [here](https://github.com/weacast/weacast-client/blob/master/src/layers/color-layer.js#L25) to your module is the `data` field you will find inside. The parameter of the scalar field passed [here](https://github.com/weacast/weacast-client/blob/master/src/layers/color-layer.js#L27) are the following for this data:
```
nCols: 370,
nRows: 260,
xllCorner: -32,
yllCorner: 20,
cellSize: 0.2
```

**Comment by VictorVelarde** [comment]
Hi,

I manually converted your test data to an ASCII grid file and then I tried to load it as a common ScalarField Layer, with v1.3.3, That throwed me a 'RangeError: Maximum call stack size exceeded', when using ` L.ScalarField.fromASCIIGrid(asc)` method. It seems that you are not using this method, but it could be a similar problem...

After replacing the 'spread operator' with a simple 'for' ([here](https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/commit/7c0acaabfec4a829ddb7102def836dd6ebeb7ea4)), it worked fine, so I have released a v1.3.4, with just that fix,

I have also prepared this [gist with your dataset](http://bl.ocks.org/VictorVelarde/raw/b53e782de187d3f61f26c5332714b380/) and v1.3.4

By now, all I can tell is that the dataset seems to be fine and that it can be loaded after the transformation.

Could you please investigate a little bit more on the issue?

**Comment by claustres** [comment]
I don't use `L.ScalarField.fromASCIIGrid(asc)` but directly the [`setData` method](https://github.com/weacast/weacast-client/blob/master/src/layers/color-layer.js#L25). So it's good to know your module works fine with my data/parameters, even if the rendering is somewhat "strange", should be something like [this](https://weacast.gitbooks.io/weacast-docs/api/LAYERS.html#colorlayer-source). I assume there is a shift in the data...

Anyway I might have a side-effect in my app, I will try to understand it.

Thanks for your support and help.

**Comment by claustres** [comment]
Your gist helped me locate the bug, I can now say that the interpolation is fine.

Before I used `cellSize` and now it seems you have to use  `cellXSize` and  `cellYSize` to specify the resolution in the scalar field.

**Comment by VictorVelarde** [comment]
Great!

I didn't think of that as an interface change, as I always use factory methods, from Gtiff or Asc, not constructor

I'm glad you found it... And also that interpolation looks fine to you.
